@URI = http://localhost:3001/api/blogs
@TYPE_JSON = Content-Type: application/json
@authorization = Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impvc2V0aGVnb2QiLCJpZCI6IjYxZGNkNDA5N2EwNmQyZjM5YzBkODg4YSIsImlhdCI6MTY0MjAwMjcwNiwiZXhwIjoxNjQyMDA2MzA2fQ.SwV7HB9dYfSGHbrGHLWVTz4kA_bgzvmIkU-lV3rt1vo
### Get all blogs
GET {{URI}} HTTP/1.1
{{TYPE_JSON}}
{{authorization}}

### Get one
GET {{URI}}/:id HTTP/1.1
{{TYPE_JSON}}

### Delete one
DELETE {{URI}}/:id HTTP/1.1
{{TYPE_JSON}}

### Create one
POST {{URI}} HTTP/1.1
{{TYPE_JSON}}
{{authorization}}

{
  "title": "Cova me hizo instalar postman"
}
